"""Platform-scoped RAG memory helpers."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class PlatformRagStore:
    """Filesystem paths for one platform's RAG store."""

    platform: str
    root: Path
    bm25_index_path: Path
    faiss_index_path: Path
    experiences_dir: Path

    def ensure_dirs(self) -> None:
        self.root.mkdir(parents=True, exist_ok=True)
        self.experiences_dir.mkdir(parents=True, exist_ok=True)


@dataclass(frozen=True)
class ExperienceArtifact:
    """Structured analysis experience persisted for later retrieval."""

    experience_id: str
    platform: str
    device_model: str
    source_log: dict[str, Any]
    created_at: str
    analysis_mode: str
    summary: dict[str, Any]
    findings: list[dict[str, Any]] = field(default_factory=list)
    rca: dict[str, Any] = field(default_factory=dict)
    evidence: dict[str, Any] = field(default_factory=dict)
    provenance: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "experience_id": self.experience_id,
            "platform": self.platform,
            "device_model": self.device_model,
            "source_log": self.source_log,
            "created_at": self.created_at,
            "analysis_mode": self.analysis_mode,
            "summary": self.summary,
            "findings": self.findings,
            "rca": self.rca,
            "evidence": self.evidence,
            "provenance": self.provenance,
        }

    def to_markdown(self) -> str:
        lines = [
            f"# Platform Experience: {self.platform}",
            "",
            f"- Experience ID: `{self.experience_id}`",
            f"- Device Model: {self.device_model}",
            f"- Analysis Mode: {self.analysis_mode}",
            f"- Created At: {self.created_at}",
            "",
            "## Summary",
            f"- Total anomalies: {self.summary.get('total_anomalies', 0)}",
            f"- Highest severity: {self.summary.get('highest_severity', 'unknown')}",
            (
                "- Affected cycles: "
                f"{', '.join(str(c) for c in self.summary.get('affected_cycles', [])) or 'none'}"
            ),
            "",
            "## RCA Short Summary",
            self.rca.get("short_summary", "N/A"),
            "",
        ]

        if self.findings:
            lines.extend(["## Findings", ""])
            for finding in self.findings:
                lines.append(
                    f"- Cycle {finding.get('cycle_id', '?')} / "
                    f"{finding.get('rule_id', 'unknown')} / "
                    f"{finding.get('severity', 'unknown')}: "
                    f"{finding.get('message', '')}"
                )
            lines.append("")

        top_templates = self.evidence.get("top_templates", [])
        if top_templates:
            lines.extend(["## Top Templates", ""])
            for template in top_templates:
                lines.append(f"- {template}")
            lines.append("")

        log_snippets = self.evidence.get("log_snippets", [])
        if log_snippets:
            lines.extend(["## Evidence Snippets", ""])
            for snippet in log_snippets:
                lines.append("```text")
                lines.append(snippet)
                lines.append("```")
            lines.append("")

        lines.extend(
            [
                "## Provenance",
                f"- Generated By: {self.provenance.get('generated_by', 'unknown')}",
                f"- Model: {self.provenance.get('model', 'n/a')}",
                f"- Confidence: {self.provenance.get('confidence', 'unknown')}",
            ]
        )
        return "\n".join(lines) + "\n"


def get_platform_rag_store(index_root: Path, platform: str) -> PlatformRagStore:
    """Resolve filesystem paths for one platform's RAG store."""
    root = index_root.expanduser() / platform
    return PlatformRagStore(
        platform=platform,
        root=root,
        bm25_index_path=root / "bm25.json",
        faiss_index_path=root / "faiss",
        experiences_dir=root / "experiences",
    )


def list_experience_docs(store: PlatformRagStore) -> list[Path]:
    """List markdown experience docs for retrieval."""
    if not store.experiences_dir.exists():
        return []
    return sorted(store.experiences_dir.glob("*.md"))


def build_experience_artifact(
    *,
    platform: str,
    device_model: str,
    logfile: Path | None,
    anomalies_data: dict[str, Any],
    drain_state: dict[str, Any],
    analysis_text: str,
    generated_by: str,
    model_name: str | None = None,
    analysis_mode: str = "agent_analyze",
) -> ExperienceArtifact:
    """Build a structured experience artifact from one analysis run."""
    findings = _extract_findings(anomalies_data)
    summary = _extract_summary(anomalies_data, findings)
    evidence = _extract_evidence(anomalies_data, drain_state)
    source_log = _build_source_log(logfile)
    fingerprint = _experience_fingerprint(platform, source_log, findings)
    return ExperienceArtifact(
        experience_id=f"{platform}-{fingerprint[:16]}",
        platform=platform,
        device_model=device_model or "unknown",
        source_log=source_log,
        created_at=datetime.now(timezone.utc).isoformat(),
        analysis_mode=analysis_mode,
        summary=summary,
        findings=findings,
        rca={"short_summary": _short_summary(analysis_text)},
        evidence=evidence,
        provenance={
            "generated_by": generated_by,
            "model": model_name or "",
            "confidence": "medium",
        },
    )


def write_experience_artifact(
    store: PlatformRagStore,
    artifact: ExperienceArtifact,
) -> tuple[Path, bool]:
    """Persist experience artifact as JSON + Markdown, skipping duplicates."""
    store.ensure_dirs()
    json_path = store.experiences_dir / f"{artifact.experience_id}.json"
    md_path = store.experiences_dir / f"{artifact.experience_id}.md"
    if json_path.exists() and md_path.exists():
        return md_path, False

    json_path.write_text(
        json.dumps(artifact.to_dict(), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    md_path.write_text(artifact.to_markdown(), encoding="utf-8")
    return md_path, True


def _extract_findings(anomalies_data: dict[str, Any], limit: int = 10) -> list[dict[str, Any]]:
    findings: list[dict[str, Any]] = []
    for trace in anomalies_data.get("traces", []):
        cycle_id = trace.get("cycle_id")
        for span in trace.get("spans", []):
            attrs = span.get("attributes", {})
            findings.append(
                {
                    "cycle_id": cycle_id,
                    "rule_id": attrs.get("anomaly.rule_id", ""),
                    "rule_name": attrs.get("anomaly.rule_name", ""),
                    "severity": attrs.get("anomaly.severity", "info"),
                    "line_number": attrs.get("anomaly.line_number", 0),
                    "message": attrs.get("anomaly.message", ""),
                }
            )
    severity_rank = {"critical": 0, "warning": 1, "info": 2}
    findings.sort(key=lambda item: (severity_rank.get(item["severity"], 99), item["cycle_id"] or 0))
    return findings[:limit]


def _extract_summary(
    anomalies_data: dict[str, Any],
    findings: list[dict[str, Any]],
) -> dict[str, Any]:
    summary = dict(anomalies_data.get("summary", {}))
    total = summary.get("total_anomalies")
    if total is None:
        total = len(findings)
    severities = [finding.get("severity", "info") for finding in findings]
    highest = "info"
    for candidate in ("critical", "warning", "info"):
        if candidate in severities:
            highest = candidate
            break
    affected = summary.get("affected_cycles")
    if affected is None:
        affected = sorted(
            {
                finding["cycle_id"]
                for finding in findings
                if finding.get("cycle_id") is not None
            }
        )
    return {
        "total_anomalies": total,
        "highest_severity": highest,
        "affected_cycles": affected,
    }


def _extract_evidence(
    anomalies_data: dict[str, Any],
    drain_state: dict[str, Any],
    *,
    max_templates: int = 5,
    max_snippets: int = 3,
) -> dict[str, Any]:
    top_templates: list[str] = []
    clusters = sorted(
        drain_state.get("clusters", []),
        key=lambda item: item.get("cluster_count", item.get("size", 0)),
        reverse=True,
    )
    for cluster in clusters[:max_templates]:
        tokens = cluster.get("log_template_tokens")
        if isinstance(tokens, list):
            top_templates.append(" ".join(tokens))
        else:
            top_templates.append(cluster.get("template", ""))

    snippets: list[str] = []
    for trace in anomalies_data.get("traces", []):
        for span in trace.get("spans", []):
            for event in span.get("events", []):
                if event.get("name") != "context":
                    continue
                attrs = event.get("attributes", {})
                before = attrs.get("log.context_before", "")
                after = attrs.get("log.context_after", "")
                snippet = "\n".join(part for part in [before, after] if part).strip()
                if snippet:
                    snippets.append(snippet)
                if len(snippets) >= max_snippets:
                    return {"top_templates": top_templates, "log_snippets": snippets}

    return {"top_templates": top_templates, "log_snippets": snippets}


def _build_source_log(logfile: Path | None) -> dict[str, Any]:
    if logfile is None or not logfile.exists():
        return {"path": "", "size_bytes": 0, "mtime_ns": 0}
    stat = logfile.stat()
    return {
        "path": str(logfile.resolve()),
        "size_bytes": stat.st_size,
        "mtime_ns": stat.st_mtime_ns,
    }


def _experience_fingerprint(
    platform: str,
    source_log: dict[str, Any],
    findings: list[dict[str, Any]],
) -> str:
    payload = {
        "platform": platform,
        "source_log": source_log,
        "findings": findings,
    }
    raw = json.dumps(payload, ensure_ascii=False, sort_keys=True).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def _short_summary(text: str) -> str:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    cleaned = [line for line in lines if not line.startswith("#")]
    if not cleaned:
        return text.strip()[:500]
    return " ".join(cleaned[:3])[:500]
